### ISSUE TITLE
Compilation Error when Updating NuGet Packages

### ISSUE THREAD

**Issue by Kornelis** [vmwareairwatchsdk/Xamarin-AWSDK#1]
When rainsing the TargetVersion to API Level 27 (8.1) and update all NuGet Packages to the latest Version I get the following Error Messages when I try to compile the solution:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		String types not allowed (at 'fontStyle' with value 'light').	XamarinAndroidSampleApp	C:\Git\Xamarin-AWSDK\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\obj\Debug\lp\2\jl\res\layout\awsdk_login_fragment_server_url_group_id.xml	7	

Error		String types not allowed (at 'fontStyle' with value 'light').	XamarinAndroidSampleApp	C:\Git\Xamarin-AWSDK\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\obj\Debug\lp\2\jl\res\layout-small-v4\saml_auth_dialog.xml	2	

Error		String types not allowed (at 'fontStyle' with value 'light').	XamarinAndroidSampleApp	C:\Git\Xamarin-AWSDK\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\obj\Debug\lp\2\jl\res\layout-small-v4\saml_auth_dialog.xml	2	

Error		String types not allowed (at 'fontStyle' with value 'light').	XamarinAndroidSampleApp	C:\Git\Xamarin-AWSDK\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\obj\Debug\lp\2\jl\res\layout\awsdk_fragment_server_url_dialog.xml	7	

Error		Original attribute defined here.	XamarinAndroidSampleApp	C:\Git\Xamarin-AWSDK\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\obj\Debug\lp\14\jl\res\values\values.xml	2	

Error		Attribute "fontStyle" already defined with incompatible format.	XamarinAndroidSampleApp	C:\Git\Xamarin-AWSDK\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\obj\Debug\lp\2\jl\res\values\values.xml	2	
`
Is there any Update planned to make the AWSDK compatible to the latest Xamarin Toolset?

**Comment by techconnaissance** [comment]
I am facing similar issue. 
AWSDK v1.3.0 in Xamarin forms Android project. Now am not able to build project. 

xxx.Android/obj/Debug/lp/2/jl/res/values/values.xml(2): error APT0000: Attribute "fontStyle" already defined with incompatible format.
xxx.Android/obj/Debug/lp/14/jl/res/values/values.xml(2): error APT0000: Original attribute defined here.
xxx.Android/obj/Debug/lp/2/jl/res/values/values.xml(4): error APT0000: No resource found that matches the given name: attr 'preferenceTheme'.

I am able to integrate AWSDK with Xamarin iOS without issue but in android unable to compile.

**Comment by MAJustice** [comment]
We are facing same issues. Not able to build  Xamarin Android project.
No problem with Xamarin iOS project.

No resource found that matches the given name: attr 'colorPrimaryDark'.	XamarinAndroidSampleApp	C:\...\Xamarin-AWSDK-master\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\Resources\values\Styles.xml	2	

No resource found that matches the given name: attr 'colorAccent'.	XamarinAndroidSampleApp	
C:\...\Xamarin-AWSDK-master\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\Resources\values\Styles.xml	2	

Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light'.	XamarinAndroidSampleApp	
C:\...\Xamarin-AWSDK-master\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\Resources\values\Styles.xml	2	

No resource found that matches the given name: attr 'colorPrimary'.	XamarinAndroidSampleApp	C:\...\Xamarin-AWSDK-master\samples\XamarinAndroidSampleApp\XamarinAndroidSampleApp\Resources\values\Styles.xml	2

**Comment by Maddy79** [comment]
Were the required packages (mentioned in the gettingstarted doc) added?

**Comment by MAJustice** [comment]
Yes, I did in a fresh project.
I downloaded the sample project and I got the same problem.

**Comment by Maddy79** [comment]
Are you using Mac OR Windows for building this?

**Comment by MAJustice** [comment]
VS 2017 Enterprise, version 15.8.9 (French version)

**Comment by MAJustice** [comment]
In Windows

**Comment by Maddy79** [comment]
ok, will be checking this on windows. Tried with Macbook VS7.5 , builds fine.

**Comment by Maddy79** [comment]
This should be working with latest packages.
