### ISSUE TITLE
Outdated instructrions for Xamarin Android

### ISSUE THREAD

**Issue by xamadev** [vmwareairwatchsdk/Xamarin-AWSDK#2]
I'm having problems implementing the Airwatch SDK with your nuget package. I think the getting started is outdatet!

I'm stuck at point 4a in the Android instructions. Because my MainActivity (you call it Application Class in the instructions) class already inherits a base class. I'm not able to inheritfrom AWApplication class.

Thank you very much for your help!

**Comment by xamadev** [comment]
For anyone else running into this issue: The Airwatch Support Team just affirmed that the this nuget package isn't compatible with Xamarin.Forms. There's a poduct requirement dated to the second half of 2019.

**Comment by Maddy79** [comment]
@xamadev , we will be coming up with Forms support within one month, will keep posted.

**Comment by xamadev** [comment]
@Maddy79 Is Xamarin.Forms now supported?

**Comment by Maddy79** [comment]
@xamadev , we have one in beta, it will be public by this week.

**Comment by Maddy79** [comment]
@xamadev , Forms package is published. Please use 8.4 VS for Mac OR Windows 16.4.
