### ISSUE TITLE
Having issues compiling iOS project is  Visual Studio 2015

### ISSUE THREAD

**Issue by mhughey-vent** [vmwareairwatchsdk/Xamarin-AWSDK#3]
I trying to compile a iOS project with Airwatch Nuget package v.1.3.1 and I'm getting inconsistent errors.

We've tried this from 2 labtops and 2 build Macs:

Laptop 1:
![specs_for_laptop_1](https://user-images.githubusercontent.com/49247207/55499139-4ac06180-5613-11e9-9724-3a47b379f372.png)

Laptop 2:
![specs_for_laptop_2](https://user-images.githubusercontent.com/49247207/55499164-590e7d80-5613-11e9-9229-e828d78cfbf7.png)

Mac 1: Sierra OS v10.12.6  ---- Xamarin.Mac v5.6.0.25  ---- Xamarin.iOS v12.6.0.25 ---- Xcode 8.3.3

Mac 2: High Sierra OS v10.13.6 ---- Xamarin.Mac v4.0.0.216 ---- Xamarin.iOS v10.12.0.20 ---- Xcode 9.0.1

We are getting errors like:

"Duplicate symbols.../iPhone/AdHoc/mtouch-cache/arm64/registrar.o"
"Duplicate symbols.../iPhone/AdHoc/mtouch-cache/AWSDK.a(....."

Can you tell me what version of Xamarin, Xcode is needed to do a successful build. Also, any frameworks that need to beinstalled in Xcode?

**Comment by Maddy79** [comment]
@mhughey-vent , is the issue still there?

**Comment by Maddy79** [comment]
Please check with latest packages
