### ISSUE TITLE
SDK initilization icon & internet access

### ISSUE THREAD

**Issue by JanSteffes** [vmwareairwatchsdk/Xamarin-AWSDK#7]
Hello again,

after some struggle with configuring ProGuard correctly, my xamarin android app seems to start working.
Now i got 2 problems, with which i still struggle.

The first problem is the icon shown during the sdk initialization prozess. I can't seem to get our app icon to appear there instead of the default one.
I found a [tutorial targeting native android ](https://code.vmware.com/web/workspace-one/tutorials/Native-Android/Airwatch-SDK), which suggests to add an attribute to the current application theme (see _Configure the App theme to have the Branding Icon_):
`
<item name="sdkBrandingIcon">@mipmap/ic_launcher</item>`

Now, if i use that attribute, i get an error doing build:
`error APT2260: style attribute 'attr/sdkBrandingIcon (aka my.company.app:attr/sdkBrandingIcon)' not found.`

So, i'm not sure what to do here, since i found no other information/guides releated to that so far.

The second problem is internet/webview access.
Our App is nothing more than a simple webview with a custom webclient for logging, that opens a specific url on startup. There will probably come some more custom/native code in the future, but thats all there is for now.
However, if i start the app now, i immediatly get an error upon requesting a webpage, say google for example:

`==> 13.11.2019 07:41:56: CustomWebViewClient.OnReceivedHttpError: request: https://www.google.de/, Error: FailedSslHandshake | net::ERR_TUNNEL_CONNECTION_FAILED`

If i watch the logs doing that request, i get something along these lines:
```

11-13 07:41:53.193 I/AirWatch(16924): WebView version : 70.0.3538.110
11-13 07:41:53.200 D/AirWatch_Proxy(16924): In lookup chained proxy
11-13 07:41:53.202 D/AirWatch_Proxy(16924): trying to check tunnelling domains for split tunnelling
11-13 07:41:53.205 D/AirWatch_Proxy(16924): App tunnel domains match
11-13 07:41:53.209 D/AirWatch_Proxy(16924): 'www.google.de:443' : tunnelling through MAG.
11-13 07:49:29.018 D/AirWatch_Proxy(16924): in proxyToServerRequest
11-13 07:49:29.018 D/AirWatch_Proxy(16924): trying to check tunnelling domains for split tunnelling
11-13 07:49:29.018 D/AirWatch_Proxy(16924): adding Proxy Auth headers
11-13 07:49:29.055 D/AirWatch_Proxy(16924): Using AirWatch custom keystore for trust management.
```

which is later followed by 

```
11-13 07:49:32.812 E/AirWatch_Proxy(16924): Error connecting to MAG.
[0:] ==> 13.11.2019 07:49:32: CustomWebViewClient.OnReceivedHttpError: request: https://www.google.de/, Error: FailedSslHandshake | net::ERR_TUNNEL_CONNECTION_FAILED
```

I've tried using a default WebView and WebClient as well as the AWWebView and AWWebClient to no avail. The app has permission to use the internet.

Is that something that i have to configure in the app or might the app need to be allowed access to the internet in the airwatch/workspace one console? So far, i did not find a documentation that cleared that up for me.

**Comment by Maddy79** [comment]
@JanSteffes , for the network error, are you installing the app via WS1 console and also is proxy enabled for the app in the SDK profile.?

For the launch screen icon issue, in the styles.xml, you can add these lines, to show your icon.

<style name="SDKBaseTheme" parent="Theme.AppCompat.Light">
        <item name="awsdkSplashBrandingIcon">@drawable/<myImageFile></item>
        <item name="awsdkLoginBrandingIcon">@drawable/<MyImageFile>t</item>
    </style>

**Comment by JanSteffes** [comment]
I will have to ask our client for the setting in the sdk profile, since we don't have access to the console.
I was debugging the app, so not directly installing via console. The app and its signing keys should be whitelisted tho.

I'll try to get the needed informations for the network error from out client in the next few days. 

Ps.: Should I post further issues/problems that i encounter while implementing the awsdk (which seem to be implementation failures by me ) also here or should i better use stackoverflow for those errors i encounter? I don't want to spam this project Issues with me sometimes not understanding the implementation guide

**Comment by Maddy79** [comment]
Directly installing app will not work, until you install whitelisted app once and launch, then use the same keys while sideloading via VS or adb.

**Comment by Maddy79** [comment]
Please install the app via Workspace ONE UEM Console.
